services:
  - type: web
    name: scrum-ai-api
    env: python
    buildCommand: cd server && pip install -r requirements.txt
    startCommand: cd server && python -m gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.3
      - key: OCTOAI_API_KEY
        sync: false